# Generated by Django 3.1.7 on 2021-03-06 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210306_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow',
            new_name='following',
        ),
    ]
